/**
 * Shared VantaCore export branding utilities.
 * Used by both OutputSection (main export) and HistorySidebar (history download).
 * Free exports always include VantaCore attribution metadata.
 * VantaCore does not claim ownership of user input or output content.
 */

export const VANTACORE_ATTRIBUTION = 'Generated by VantaCore - Portable Memory Capsules for LLMs.'
export const VANTACORE_POSITIONING = 'Compress massive AI sessions into portable memory capsules. 100% client-side.'
export const CONTENT_OWNERSHIP_NOTE = 'VantaCore does not claim ownership of your input or output content.'

export interface ExportableStats {
  originalChars: number
  compressedChars: number
  reductionPercent: number
  estimatedTokensBefore: number
  estimatedTokensAfter: number
  tokenEstimationMethod: string
  repeatedBlocksFolded: number
  dictionaryReferencesCreated: number
  clustersDetected: number
  codeBlocksProtected: number
  codeBlocksIntegrityOk: boolean
}

export const markdownExportFromCompressed = (compressed: string) => `---
generator: VantaCore
generator_url: https://vantacore.net
format: memory-capsule
license_note: Free export includes attribution.
ownership_note: ${CONTENT_OWNERSHIP_NOTE}
---

<!--
${VANTACORE_ATTRIBUTION}
${VANTACORE_POSITIONING}
https://vantacore.net

Free export includes VantaCore attribution.
${CONTENT_OWNERSHIP_NOTE}
-->

${compressed}

---

${VANTACORE_ATTRIBUTION}
${VANTACORE_POSITIONING}
https://vantacore.net
${CONTENT_OWNERSHIP_NOTE}
`

export const textExportFromCompressed = (compressed: string) => `${VANTACORE_ATTRIBUTION}
${VANTACORE_POSITIONING}
https://vantacore.net
${CONTENT_OWNERSHIP_NOTE}

---

${compressed}

---

${VANTACORE_ATTRIBUTION}
${CONTENT_OWNERSHIP_NOTE}
`

export const jsonExportFromCompressed = (compressed: string, stats?: ExportableStats) => JSON.stringify({
  generator: 'VantaCore',
  generator_url: 'https://vantacore.net',
  format: 'memory-capsule',
  license_note: 'Free export includes attribution.',
  ownership_note: CONTENT_OWNERSHIP_NOTE,
  pro_hooks: {
    branding_removal_available: false,
  },
  compressed,
  ...(stats ? {
    stats: {
      originalChars: stats.originalChars,
      compressedChars: stats.compressedChars,
      reductionPercent: stats.reductionPercent,
      estimatedTokensBefore: stats.estimatedTokensBefore,
      estimatedTokensAfter: stats.estimatedTokensAfter,
      tokenEstimationMethod: stats.tokenEstimationMethod,
      repeatedBlocksFolded: stats.repeatedBlocksFolded,
      dictionaryReferencesCreated: stats.dictionaryReferencesCreated,
      clustersDetected: stats.clustersDetected,
      codeBlocksProtected: stats.codeBlocksProtected,
      codeBlocksIntegrityOk: stats.codeBlocksIntegrityOk,
    },
  } : {}),
}, null, 2)

/**
 * Get branded export content for a given extension.
 * Supports .md, .txt, .json.
 */
export function getExportContent(ext: string, compressed: string, stats?: ExportableStats): string {
  if (ext === '.json') return jsonExportFromCompressed(compressed, stats)
  if (ext === '.md') return markdownExportFromCompressed(compressed)
  return textExportFromCompressed(compressed)
}

/**
 * Trigger a browser download from a string content, without touching any app state.
 */
export function downloadStringAsFile(content: string, filename: string, ext: string) {
  const mimeType = ext === '.json' ? 'application/json' : 'text/plain'
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
