/**
 * Shared VantaCore export branding utilities.
 * Used by both OutputSection (main export) and HistorySidebar (history download).
 * Free exports always include VantaCore attribution metadata.
 * VantaCore does not claim ownership of user input or output content.
 */

export const VANTACORE_ATTRIBUTION = 'Generated by VantaCore - Portable Memory Capsules for LLMs.'
export const VANTACORE_POSITIONING = 'Compress massive AI sessions into portable memory capsules. 100% client-side.'
export const CONTENT_OWNERSHIP_NOTE = 'VantaCore does not claim ownership of your input or output content.'
export const VANTACORE_APP_NAME = 'VantaCore'
export const VANTACORE_APP_VERSION = '4.5.0-unreleased'
export const CAPSULE_FORMAT = 'memory-capsule'
export const CAPSULE_FORMAT_VERSION = '1.1'
export const EXPORT_SCHEMA_VERSION = '1.1'

export interface ExportableStats {
  originalChars: number
  compressedChars: number
  reductionPercent: number
  estimatedTokensBefore: number
  estimatedTokensAfter: number
  tokenEstimationMethod: string
  repeatedBlocksFolded: number
  dictionaryReferencesCreated: number
  clustersDetected: number
  codeBlocksProtected: number
  codeBlocksIntegrityOk: boolean
}

export interface ExportMetadataOptions {
  exportFormat?: string
  compressionProfile?: string
  sourceProfile?: string
  sourceMode?: string
  generatedAt?: string
}

interface CapsuleExportMetadata {
  generator: string
  generator_url: string
  app_name: string
  app_version: string
  format: string
  capsule_format: string
  capsule_format_version: string
  export_schema_version: string
  export_format: string
  generated_at: string
  compression_profile: string
  source_profile: string
  source_mode: string
  token_estimation_method: string
  import_compatible: boolean
  import_notes: string
  ownership_note: string
  license_note: string
}

const DEFAULT_IMPORT_NOTES = 'Import this file through VantaCore Import Capsule. Restore is client-side and does not consume compression quota.'

const yamlString = (value: string) => JSON.stringify(value)

function buildExportMetadata(
  exportFormat: string,
  stats?: ExportableStats,
  options: ExportMetadataOptions = {}
): CapsuleExportMetadata {
  const sourceMode = options.sourceMode ?? options.sourceProfile ?? options.compressionProfile ?? 'memory-capsule'

  return {
    generator: VANTACORE_APP_NAME,
    generator_url: 'https://vantacore.net',
    app_name: VANTACORE_APP_NAME,
    app_version: VANTACORE_APP_VERSION,
    format: CAPSULE_FORMAT,
    capsule_format: CAPSULE_FORMAT,
    capsule_format_version: CAPSULE_FORMAT_VERSION,
    export_schema_version: EXPORT_SCHEMA_VERSION,
    export_format: options.exportFormat ?? exportFormat,
    generated_at: options.generatedAt ?? new Date().toISOString(),
    compression_profile: options.compressionProfile ?? sourceMode,
    source_profile: options.sourceProfile ?? sourceMode,
    source_mode: sourceMode,
    token_estimation_method: stats?.tokenEstimationMethod ?? 'approximate: ceil(characters / 4)',
    import_compatible: true,
    import_notes: DEFAULT_IMPORT_NOTES,
    ownership_note: CONTENT_OWNERSHIP_NOTE,
    license_note: 'Free export includes attribution.',
  }
}

const statsForJson = (stats: ExportableStats) => ({
  originalChars: stats.originalChars,
  compressedChars: stats.compressedChars,
  reductionPercent: stats.reductionPercent,
  estimatedTokensBefore: stats.estimatedTokensBefore,
  estimatedTokensAfter: stats.estimatedTokensAfter,
  tokenEstimationMethod: stats.tokenEstimationMethod,
  repeatedBlocksFolded: stats.repeatedBlocksFolded,
  dictionaryReferencesCreated: stats.dictionaryReferencesCreated,
  clustersDetected: stats.clustersDetected,
  codeBlocksProtected: stats.codeBlocksProtected,
  codeBlocksIntegrityOk: stats.codeBlocksIntegrityOk,
})

export const markdownExportFromCompressed = (
  compressed: string,
  stats?: ExportableStats,
  options?: ExportMetadataOptions
) => {
  const metadata = buildExportMetadata('markdown', stats, options)

  return `---
generator: ${yamlString(metadata.generator)}
generator_url: ${yamlString(metadata.generator_url)}
app_name: ${yamlString(metadata.app_name)}
app_version: ${yamlString(metadata.app_version)}
format: ${yamlString(metadata.format)}
capsule_format: ${yamlString(metadata.capsule_format)}
capsule_format_version: ${yamlString(metadata.capsule_format_version)}
export_schema_version: ${yamlString(metadata.export_schema_version)}
export_format: ${yamlString(metadata.export_format)}
generated_at: ${yamlString(metadata.generated_at)}
compression_profile: ${yamlString(metadata.compression_profile)}
source_profile: ${yamlString(metadata.source_profile)}
source_mode: ${yamlString(metadata.source_mode)}
token_estimation_method: ${yamlString(metadata.token_estimation_method)}
import_compatible: ${metadata.import_compatible}
import_notes: ${yamlString(metadata.import_notes)}
license_note: ${yamlString(metadata.license_note)}
ownership_note: ${yamlString(metadata.ownership_note)}
---

<!--
${VANTACORE_ATTRIBUTION}
${VANTACORE_POSITIONING}
https://vantacore.net
app_version: ${metadata.app_version}
capsule_format_version: ${metadata.capsule_format_version}
export_schema_version: ${metadata.export_schema_version}
export_format: ${metadata.export_format}
source_mode: ${metadata.source_mode}
import_compatible: ${metadata.import_compatible}

Free export includes VantaCore attribution.
${CONTENT_OWNERSHIP_NOTE}
-->

${compressed}

---

${VANTACORE_ATTRIBUTION}
${VANTACORE_POSITIONING}
https://vantacore.net
${CONTENT_OWNERSHIP_NOTE}
`
}

export const textExportFromCompressed = (
  compressed: string,
  stats?: ExportableStats,
  options?: ExportMetadataOptions
) => {
  const metadata = buildExportMetadata('text', stats, options)

  return `${VANTACORE_ATTRIBUTION}
${VANTACORE_POSITIONING}
https://vantacore.net
${CONTENT_OWNERSHIP_NOTE}

app_name: ${metadata.app_name}
app_version: ${metadata.app_version}
capsule_format: ${metadata.capsule_format}
capsule_format_version: ${metadata.capsule_format_version}
export_schema_version: ${metadata.export_schema_version}
export_format: ${metadata.export_format}
generated_at: ${metadata.generated_at}
compression_profile: ${metadata.compression_profile}
source_profile: ${metadata.source_profile}
source_mode: ${metadata.source_mode}
token_estimation_method: ${metadata.token_estimation_method}
import_compatible: ${metadata.import_compatible}
import_notes: ${metadata.import_notes}

---

${compressed}

---

${VANTACORE_ATTRIBUTION}
${CONTENT_OWNERSHIP_NOTE}
`
}

export const jsonExportFromCompressed = (
  compressed: string,
  stats?: ExportableStats,
  options?: ExportMetadataOptions
) => JSON.stringify({
  ...buildExportMetadata('json', stats, options),
  pro_hooks: {
    branding_removal_available: false,
  },
  compressed,
  ...(stats ? { stats: statsForJson(stats) } : {}),
}, null, 2)

/**
 * Get branded export content for a given extension.
 * Supports .md, .txt, .json.
 */
export function getExportContent(
  ext: string,
  compressed: string,
  stats?: ExportableStats,
  options?: ExportMetadataOptions
): string {
  if (ext === '.json') return jsonExportFromCompressed(compressed, stats, options)
  if (ext === '.md') return markdownExportFromCompressed(compressed, stats, options)
  return textExportFromCompressed(compressed, stats, options)
}

/**
 * Trigger a browser download from a string content, without touching any app state.
 */
export function downloadStringAsFile(content: string, filename: string, ext: string) {
  const mimeType = ext === '.json' ? 'application/json' : 'text/plain'
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
